DROP TABLE IF EXISTS `database`.`drop_list`;
CREATE TABLE  `database`.`drop_list` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `dropperid` int(10) unsigned NOT NULL,
  `itemid` int(10) unsigned NOT NULL,
  `min_qtd` int(10) unsigned NOT NULL,
  `max_qtd` int(10) unsigned NOT NULL,
  `quest` int(10) unsigned NOT NULL,
  `chance` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `database`.`equips`;
CREATE TABLE  `database`.`equips` (
  `itemid` int(10) unsigned NOT NULL,
  `islot` varchar(45) NOT NULL,
  `vslot` varchar(45) NOT NULL,
  `reqJob` int(10) unsigned NOT NULL,
  `reqLevel` int(10) unsigned NOT NULL,
  `reqSTR` int(10) unsigned NOT NULL,
  `reqDEX` int(10) unsigned NOT NULL,
  `reqINT` int(10) unsigned NOT NULL,
  `reqLUK` int(10) unsigned NOT NULL,
  `cash` int(10) unsigned NOT NULL,
  `incSTR` int(10) unsigned NOT NULL,
  `timeLimited` int(10) unsigned NOT NULL,
  `tuc` int(10) unsigned NOT NULL,
  `incDEX` int(10) unsigned NOT NULL,
  `incINT` int(10) unsigned NOT NULL,
  `incPAD` int(10) unsigned NOT NULL,
  `incPDD` int(10) unsigned NOT NULL,
  `incMAD` int(10) unsigned NOT NULL,
  `incMDD` int(10) unsigned NOT NULL,
  `incEVA` int(10) unsigned NOT NULL,
  `incACC` int(10) unsigned NOT NULL,
  `tradeBlock` int(10) unsigned NOT NULL,
  `price` int(10) unsigned NOT NULL,
  `slotMax` int(10) unsigned NOT NULL,
  `notSale` int(10) unsigned NOT NULL,
  `incSpeed` int(10) unsigned NOT NULL,
  `incJump` int(10) unsigned NOT NULL,
  `only` int(10) unsigned NOT NULL,
  `incMHP` int(10) unsigned NOT NULL,
  `incMMP` int(10) unsigned NOT NULL,
  `onlyEquip` int(10) unsigned NOT NULL,
  `tradeAvailable` int(10) unsigned NOT NULL,
  `equipTradeBlock` int(10) unsigned NOT NULL,
  `tradBlock` int(10) unsigned NOT NULL,
  `MaxHP` int(10) unsigned NOT NULL,
  `medalTag` int(10) unsigned NOT NULL,
  `notExtend` int(10) unsigned NOT NULL,
  `incCraft` int(10) unsigned NOT NULL,
  `specialID` int(10) unsigned NOT NULL,
  `speed` int(10) unsigned NOT NULL,
  `expireOnLogout` int(10) unsigned NOT NULL,
  `reqPOP` int(10) unsigned NOT NULL,
  `quest` int(10) unsigned NOT NULL,
  `pachinko` int(10) unsigned NOT NULL,
  `acc` int(10) unsigned NOT NULL,
  `weekly` int(10) unsigned NOT NULL,
  `incHP` int(10) unsigned NOT NULL,
  `epicItem` int(10) unsigned NOT NULL,
  `sample` longtext NOT NULL,
  `incLUk` int(10) unsigned NOT NULL,
  `pickupMeso` varchar(45) NOT NULL,
  `pickupItem` varchar(45) NOT NULL,
  `pickupOthers` varchar(45) NOT NULL,
  `sweepForDrop` varchar(45) NOT NULL,
  `consumeHP` varchar(45) NOT NULL,
  `longRange` varchar(45) NOT NULL,
  `consumeMP` varchar(45) NOT NULL,
  `ignorePickup` int(10) unsigned NOT NULL,
  `nameTag` int(10) unsigned NOT NULL,
  `chatBalloon` int(10) unsigned NOT NULL,
  `accountSharable` int(10) unsigned NOT NULL,
  `fs` int(10) unsigned NOT NULL,
  `tamingMob` int(10) unsigned NOT NULL,
  `incSwim` int(10) unsigned NOT NULL,
  `incFatigue` int(10) unsigned NOT NULL,
  `hpRecovery` int(10) unsigned NOT NULL,
  `mpRecovery` int(10) unsigned NOT NULL,
  `afterImage` varchar(45) NOT NULL,
  `sfx` varchar(45) NOT NULL,
  `walk` int(10) unsigned NOT NULL,
  `stand` int(10) unsigned NOT NULL,
  `attackSpeed` int(10) unsigned NOT NULL,
  `incRMAF` int(10) unsigned NOT NULL,
  `incRMAS` int(10) unsigned NOT NULL,
  `elemDefault` int(10) unsigned NOT NULL,
  `incRMAI` int(10) unsigned NOT NULL,
  `incRMAL` int(10) unsigned NOT NULL,
  `hide` int(10) unsigned NOT NULL,
  `knockback` int(10) unsigned NOT NULL,
  `name` text NOT NULL,
  `descr` longtext NOT NULL,
  `url` text NOT NULL,
  PRIMARY KEY (`itemid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `database`.`items`;
CREATE TABLE  `database`.`items` (
  `itemid` int(10) unsigned NOT NULL,
  `cash` int(10) unsigned NOT NULL,
  `noFlip` varchar(45) NOT NULL,
  `slotMax` int(10) unsigned NOT NULL,
  `soldInform` int(10) unsigned NOT NULL,
  `protectTime` int(10) unsigned NOT NULL,
  `path` varchar(45) NOT NULL,
  `type` int(10) unsigned NOT NULL,
  `floatType` int(10) unsigned NOT NULL,
  `tradeBlock` int(10) unsigned NOT NULL,
  `speed` int(10) unsigned NOT NULL,
  `direction` int(10) unsigned NOT NULL,
  `stateChangeItem` int(10) unsigned NOT NULL,
  `0` int(10) unsigned NOT NULL,
  `bgmPath` varchar(45) NOT NULL,
  `isBgmOrEffect` int(10) unsigned NOT NULL,
  `Rrepeat` int(10) unsigned NOT NULL,
  `recoveryRate` int(10) unsigned NOT NULL,
  `life` int(10) unsigned NOT NULL,
  `pickupItem` int(10) unsigned NOT NULL,
  `Radd` int(10) unsigned NOT NULL,
  `consumeHP` int(10) unsigned NOT NULL,
  `longRange` int(10) unsigned NOT NULL,
  `dropSweep` int(10) unsigned NOT NULL,
  `pickupAll` int(10) unsigned NOT NULL,
  `ignorePickup` int(10) unsigned NOT NULL,
  `consumeMP` int(10) unsigned NOT NULL,
  `recall` int(10) unsigned NOT NULL,
  `autoSpeaking` int(10) unsigned NOT NULL,
  `meso` int(10) unsigned NOT NULL,
  `rate` int(10) unsigned NOT NULL,
  `pachinko` int(10) unsigned NOT NULL,
  `time` int(10) unsigned NOT NULL,
  `price` int(10) unsigned NOT NULL,
  `sample` longtext NOT NULL,
  `emotion` int(10) unsigned NOT NULL,
  `npc` int(10) unsigned NOT NULL,
  `randomMoveInFieldSet` int(10) unsigned NOT NULL,
  `expBuff` int(10) unsigned NOT NULL,
  `addTime` int(10) unsigned NOT NULL,
  `maxDays` int(10) unsigned NOT NULL,
  `slotIndex` int(10) unsigned NOT NULL,
  `addDay` int(10) unsigned NOT NULL,
  `incLEV` int(10) unsigned NOT NULL,
  `notSale` int(10) unsigned NOT NULL,
  `quest` int(10) unsigned NOT NULL,
  `timeLimited` int(10) unsigned NOT NULL,
  `mcType` int(10) unsigned NOT NULL,
  `effect` varchar(45) NOT NULL,
  `only` int(10) unsigned NOT NULL,
  `tradBlock` int(10) unsigned NOT NULL,
  `bigSize` int(10) unsigned NOT NULL,
  `pquest` int(10) unsigned NOT NULL,
  `tragetBlock` int(10) unsigned NOT NULL,
  `noCancelMouse` int(10) unsigned NOT NULL,
  `scanTradeBlock` int(10) unsigned NOT NULL,
  `max` int(10) unsigned NOT NULL,
  `incPDD` int(10) unsigned NOT NULL,
  `success` int(10) unsigned NOT NULL,
  `incMDD` int(10) unsigned NOT NULL,
  `incACC` int(10) unsigned NOT NULL,
  `incMHP` int(10) unsigned NOT NULL,
  `icon_link` int(10) unsigned NOT NULL,
  `iconRaw_link` int(10) unsigned NOT NULL,
  `cursed` int(10) unsigned NOT NULL,
  `incINT` int(10) unsigned NOT NULL,
  `incDEX` int(10) unsigned NOT NULL,
  `incMAD` int(10) unsigned NOT NULL,
  `incPAD` int(10) unsigned NOT NULL,
  `incEVA` int(10) unsigned NOT NULL,
  `incSTR` int(10) unsigned NOT NULL,
  `incLUK` int(10) unsigned NOT NULL,
  `incSpeed` int(10) unsigned NOT NULL,
  `incMMP` int(10) unsigned NOT NULL,
  `incJump` int(10) unsigned NOT NULL,
  `preventslip` int(10) unsigned NOT NULL,
  `warmsupport` int(10) unsigned NOT NULL,
  `reqRUC` int(10) unsigned NOT NULL,
  `recover` int(10) unsigned NOT NULL,
  `reqLevel` int(10) unsigned NOT NULL,
  `random` int(10) unsigned NOT NULL,
  `mob` int(10) unsigned NOT NULL,
  `Rcreate` int(10) unsigned NOT NULL,
  `Rleft` int(10) unsigned NOT NULL,
  `Rright` int(10) unsigned NOT NULL,
  `top` int(10) unsigned NOT NULL,
  `bottom` int(10) unsigned NOT NULL,
  `mobHP` int(10) unsigned NOT NULL,
  `bridleMsgType` int(10) unsigned NOT NULL,
  `bridleProp` int(10) unsigned NOT NULL,
  `useDelay` int(10) unsigned NOT NULL,
  `delayMsg` varchar(45) NOT NULL,
  `masterLevel` int(10) unsigned NOT NULL,
  `tradeAvailable` int(10) unsigned NOT NULL,
  `reqSkillLevel` int(10) unsigned NOT NULL,
  `maxLevel` int(10) unsigned NOT NULL,
  `monsterBook` int(10) unsigned NOT NULL,
  `lv` int(10) unsigned NOT NULL,
  `pickUpBlock` int(10) unsigned NOT NULL,
  `showMessage` int(10) unsigned NOT NULL,
  `exp` int(10) unsigned NOT NULL,
  `consumeOnPickup` int(10) unsigned NOT NULL,
  `script` varchar(45) NOT NULL,
  `notExtend` int(10) unsigned NOT NULL,
  `slotMat` int(10) unsigned NOT NULL,
  `expireOnLogout` int(10) unsigned NOT NULL,
  `name` varchar(45) NOT NULL,
  `descr` longtext NOT NULL,
  `url` text NOT NULL,
  `uiData` varchar(45) NOT NULL,
  `grade` int(10) unsigned NOT NULL,
  `questId` int(10) unsigned NOT NULL,
  `hybrid` int(10) unsigned NOT NULL,
  `incMaxHP` int(10) unsigned NOT NULL,
  `incMaxMP` int(10) unsigned NOT NULL,
  `incReqLevel` int(10) unsigned NOT NULL,
  `randOption` int(10) unsigned NOT NULL,
  `randStat` int(10) unsigned NOT NULL,
  `lvMin` int(10) unsigned NOT NULL,
  `lvMax` int(10) unsigned NOT NULL,
  `recoveryHP` int(10) unsigned NOT NULL,
  `recoveryMP` int(10) unsigned NOT NULL,
  `distanceX` int(10) unsigned NOT NULL,
  `distanceY` int(10) unsigned NOT NULL,
  `maxDiff` int(10) unsigned NOT NULL,
  `iconD` longtext NOT NULL,
  `iconRawD` longtext NOT NULL,
  `hungry` int(10) unsigned NOT NULL,
  `nameTag` int(10) unsigned NOT NULL,
  `chatBalloon` int(10) unsigned NOT NULL,
  `evol` int(10) unsigned NOT NULL,
  `evol1` int(10) unsigned NOT NULL,
  `evolReqItemID` int(10) unsigned NOT NULL,
  `evolNo` int(10) unsigned NOT NULL,
  `evolProb1` int(10) unsigned NOT NULL,
  `evol2` int(10) unsigned NOT NULL,
  `evol3` int(10) unsigned NOT NULL,
  `evol4` int(10) unsigned NOT NULL,
  `evolProb2` int(10) unsigned NOT NULL,
  `evolProb3` int(10) unsigned NOT NULL,
  `evolProb4` int(10) unsigned NOT NULL,
  `evolReqPetLvl` int(10) unsigned NOT NULL,
  `autoReact` int(10) unsigned NOT NULL,
  `evol5` int(10) unsigned NOT NULL,
  `evolProb5` int(10) unsigned NOT NULL,
  `limitedLife` int(10) unsigned NOT NULL,
  `noRevive` int(10) unsigned NOT NULL,
  `noMoveToLocker` int(10) unsigned NOT NULL,
  `permanent` int(10) unsigned NOT NULL,
  `itemtype` varchar(45) NOT NULL,
  `inc` int(10) unsigned NOT NULL,
  `hp` int(10) unsigned NOT NULL,
  `morph` int(10) unsigned NOT NULL,
  `mp` int(10) unsigned NOT NULL,
  `moveTo` int(10) unsigned NOT NULL,
  `poison` int(10) unsigned NOT NULL,
  `incFatigue` int(10) unsigned NOT NULL,
  `ghost` int(10) unsigned NOT NULL,
  `hpR` int(10) unsigned NOT NULL,
  `mpR` int(10) unsigned NOT NULL,
  `eva` int(10) unsigned NOT NULL,
  `mad` int(10) unsigned NOT NULL,
  `pad` int(10) unsigned NOT NULL,
  `acc` int(10) unsigned NOT NULL,
  `pdd` int(10) unsigned NOT NULL,
  `mdd` int(10) unsigned NOT NULL,
  `thaw` int(10) unsigned NOT NULL,
  `jump` int(10) unsigned NOT NULL,
  `mesoupbyitem` int(10) unsigned NOT NULL,
  `prob` int(10) unsigned NOT NULL,
  `cp` int(10) unsigned NOT NULL,
  `party` int(10) unsigned NOT NULL,
  `seal` int(10) unsigned NOT NULL,
  `darkness` int(10) unsigned NOT NULL,
  `weakness` int(10) unsigned NOT NULL,
  `curse` int(10) unsigned NOT NULL,
  `nuffSkill` int(10) unsigned NOT NULL,
  `barrier` int(10) unsigned NOT NULL,
  `onlyPickup` int(10) unsigned NOT NULL,
  `padRate` int(10) unsigned NOT NULL,
  `madRate` int(10) unsigned NOT NULL,
  `pddRate` int(10) unsigned NOT NULL,
  `mddRate` int(10) unsigned NOT NULL,
  `accRate` int(10) unsigned NOT NULL,
  `evaRate` int(10) unsigned NOT NULL,
  `speedRate` int(10) unsigned NOT NULL,
  `mhpR` int(10) unsigned NOT NULL,
  `mhpRRate` int(10) unsigned NOT NULL,
  `mmpR` int(10) unsigned NOT NULL,
  `mmpRRate` int(10) unsigned NOT NULL,
  `dojangshield` int(10) unsigned NOT NULL,
  `expinc` int(10) unsigned NOT NULL,
  `itemupbyitem` int(10) unsigned NOT NULL,
  `eventPoint` int(10) unsigned NOT NULL,
  `eventRate` int(10) unsigned NOT NULL,
  `BFSkill` int(10) unsigned NOT NULL,
  `booster` int(10) unsigned NOT NULL,
  `berserk` int(10) unsigned NOT NULL,
  `repeatEffect` int(10) unsigned NOT NULL,
  `returnMapQR` int(10) unsigned NOT NULL,
  `ignoreContinent` int(10) unsigned NOT NULL,
  `itemCode` int(10) unsigned NOT NULL,
  `defenseAtt` varchar(45) NOT NULL,
  `itemRange` int(10) unsigned NOT NULL,
  `defenseState` varchar(45) NOT NULL,
  `respectFS` int(10) unsigned NOT NULL,
  `respectMimmune` int(10) unsigned NOT NULL,
  `respectPimmune` int(10) unsigned NOT NULL,
  `runOnPickup` int(10) unsigned NOT NULL,
  PRIMARY KEY (`itemid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `database`.`maps`;
CREATE TABLE  `database`.`maps` (
  `mapid` int(10) unsigned NOT NULL,
  `bgm` varchar(45) NOT NULL,
  `mapMark` varchar(45) NOT NULL,
  `onFirstUserEnter` varchar(45) NOT NULL,
  `onUserEnter` varchar(45) NOT NULL,
  `version` int(10) unsigned NOT NULL,
  `cloud` int(10) unsigned NOT NULL,
  `town` int(10) unsigned NOT NULL,
  `swim` int(10) unsigned NOT NULL,
  `returnMap` int(10) unsigned NOT NULL,
  `forcedReturn` int(10) unsigned NOT NULL,
  `fly` int(10) unsigned NOT NULL,
  `noMapCmd` int(10) unsigned NOT NULL,
  `hideMinimap` int(10) unsigned NOT NULL,
  `fieldLimit` int(10) unsigned NOT NULL,
  `VRTop` int(10) unsigned NOT NULL,
  `VRLeft` int(10) unsigned NOT NULL,
  `VRBottom` int(10) unsigned NOT NULL,
  `VRRight` int(10) unsigned NOT NULL,
  `fieldType` int(10) unsigned NOT NULL,
  `mapDesc` longtext NOT NULL,
  `moveLimit` int(10) unsigned NOT NULL,
  `streetName` longtext NOT NULL,
  `mapName` longtext NOT NULL,
  `miniMapOnOff` int(10) unsigned NOT NULL,
  `timeLimit` int(10) unsigned NOT NULL,
  `link` varchar(45) NOT NULL,
  `help` varchar(45) NOT NULL,
  `lvLimit` int(10) unsigned NOT NULL,
  `snow` int(10) unsigned NOT NULL,
  `rain` int(10) unsigned NOT NULL,
  `lvForceMove` int(10) unsigned NOT NULL,
  `decHP` int(10) unsigned NOT NULL,
  `decInterval` int(10) unsigned NOT NULL,
  `protectItem` int(10) unsigned NOT NULL,
  `dropExpire` int(10) unsigned NOT NULL,
  `effect` varchar(45) NOT NULL,
  `VRLimit` int(10) unsigned NOT NULL,
  `everlast` int(10) unsigned NOT NULL,
  `scrollDisable` int(10) unsigned NOT NULL,
  `partyOnly` int(10) unsigned NOT NULL,
  `allMoveCheck` int(10) unsigned NOT NULL,
  `zakum2Hack` int(10) unsigned NOT NULL,
  `timeOut` int(10) unsigned NOT NULL,
  `noRegenMap` int(10) unsigned NOT NULL,
  `reactorShuffle` int(10) unsigned NOT NULL,
  `personalShop` int(10) unsigned NOT NULL,
  `entrustedShop` int(10) unsigned NOT NULL,
  `fixedMobCapacity` int(10) unsigned NOT NULL,
  `createMobInterval` int(10) unsigned NOT NULL,
  `reactorShuffleName` varchar(45) NOT NULL,
  `damageCheckFree` int(10) unsigned NOT NULL,
  `blockPBossChange` int(10) unsigned NOT NULL,
  `url` text NOT NULL,
  `continent` int(10) unsigned NOT NULL,
  PRIMARY KEY (`mapid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `database`.`maps_life`;
CREATE TABLE  `database`.`maps_life` (
  `lifeid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `mapid` int(10) unsigned NOT NULL,
  `type` varchar(45) NOT NULL,
  `id` int(10) unsigned NOT NULL,
  `x` int(10) unsigned NOT NULL,
  `y` int(10) unsigned NOT NULL,
  `mobTime` int(10) unsigned NOT NULL,
  `f` int(10) unsigned NOT NULL,
  `hide` int(10) unsigned NOT NULL,
  `fh` int(10) unsigned NOT NULL,
  `cy` int(10) unsigned NOT NULL,
  `rx0` int(10) unsigned NOT NULL,
  `rx1` int(10) unsigned NOT NULL,
  `limitedname` varchar(45) NOT NULL,
  `info` int(10) unsigned NOT NULL,
  `team` int(10) unsigned NOT NULL,
  PRIMARY KEY (`lifeid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `database`.`maps_portals`;
CREATE TABLE  `database`.`maps_portals` (
  `portalid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `mapid` int(10) unsigned NOT NULL,
  `pn` varchar(45) NOT NULL,
  `tn` varchar(45) NOT NULL,
  `pt` int(10) unsigned NOT NULL,
  `x` int(10) unsigned NOT NULL,
  `y` int(10) unsigned NOT NULL,
  `tm` int(10) unsigned NOT NULL,
  `image` varchar(45) NOT NULL,
  `script` varchar(45) NOT NULL,
  `horizontalImpact` int(10) unsigned NOT NULL,
  `delay` int(10) unsigned NOT NULL,
  `hideTooltip` int(10) unsigned NOT NULL,
  `onlyOnce` int(10) unsigned NOT NULL,
  `hRange` int(10) unsigned NOT NULL,
  `vRange` int(10) unsigned NOT NULL,
  `verticalImpact` int(10) unsigned NOT NULL,
  `f` int(10) unsigned NOT NULL,
  PRIMARY KEY (`portalid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `database`.`mobs`;
CREATE TABLE  `database`.`mobs` (
  `mobid` int(10) unsigned NOT NULL,
  `level` int(10) unsigned NOT NULL,
  `maxHP` int(10) unsigned NOT NULL,
  `maxMP` int(10) unsigned NOT NULL,
  `PADamage` int(10) unsigned NOT NULL,
  `PDDamage` int(10) unsigned NOT NULL,
  `MADamage` int(10) unsigned NOT NULL,
  `MDDamage` int(10) unsigned NOT NULL,
  `acc` int(10) unsigned NOT NULL,
  `eva` int(10) unsigned NOT NULL,
  `exp` int(10) unsigned NOT NULL,
  `undead` int(10) unsigned NOT NULL,
  `pushed` int(10) unsigned NOT NULL,
  `summonType` int(10) unsigned NOT NULL,
  `mobType` int(10) unsigned NOT NULL,
  `fs` float NOT NULL,
  `elemAttr` varchar(45) NOT NULL,
  `hpRecovery` int(10) unsigned NOT NULL,
  `mpRecovery` int(10) unsigned NOT NULL,
  `hpTagColor` int(10) unsigned NOT NULL,
  `hpTagBgcolor` int(10) unsigned NOT NULL,
  `boss` int(10) unsigned NOT NULL,
  `HPgaugeHide` int(10) unsigned NOT NULL,
  `rareItemDropLevel` int(10) unsigned NOT NULL,
  `link` varchar(45) NOT NULL,
  `explosiveReward` int(10) unsigned NOT NULL,
  `removeAfter` int(10) unsigned NOT NULL,
  `noFlip` int(10) unsigned NOT NULL,
  `mbookID` int(10) unsigned NOT NULL,
  `chaseSpeed` int(10) unsigned NOT NULL,
  `noregen` int(10) unsigned NOT NULL,
  `Speed` int(10) unsigned NOT NULL,
  `publicReward` int(10) unsigned NOT NULL,
  `defaultHP` varchar(45) NOT NULL,
  `defaultMP` varchar(45) NOT NULL,
  `buff` varchar(45) NOT NULL,
  `disable` int(10) unsigned NOT NULL,
  `hideHP` int(10) unsigned NOT NULL,
  `invincible` int(10) unsigned NOT NULL,
  `notAttack` int(10) unsigned NOT NULL,
  `damagedByMob` int(10) unsigned NOT NULL,
  `dropItemPeriod` int(10) unsigned NOT NULL,
  `getCP` int(10) unsigned NOT NULL,
  `doNotRemove` int(10) unsigned NOT NULL,
  `ignoreFieldOut` int(10) unsigned NOT NULL,
  `fixedDamage` int(10) unsigned NOT NULL,
  `fixDamage` int(10) unsigned NOT NULL,
  `onlyNormalAttack` int(10) unsigned NOT NULL,
  `0` int(10) unsigned NOT NULL,
  `hidename` int(10) unsigned NOT NULL,
  `cantPassByTeleport` int(10) unsigned NOT NULL,
  `weapon` int(10) unsigned NOT NULL,
  `ChargeCount` int(10) unsigned NOT NULL,
  `AngerGauge` int(10) unsigned NOT NULL,
  `firstattack` int(10) unsigned NOT NULL,
  `FlySpeed` int(10) unsigned NOT NULL,
  `removeQuest` int(10) unsigned NOT NULL,
  `bodyattack` int(10) unsigned NOT NULL,
  `removeOnMiss` int(10) unsigned NOT NULL,
  `coolDamage` int(10) unsigned NOT NULL,
  `coolDamageProb` int(10) unsigned NOT NULL,
  `point` int(10) unsigned NOT NULL,
  `name` text NOT NULL,
  `url` text NOT NULL,
  PRIMARY KEY (`mobid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `database`.`news`;
CREATE TABLE  `database`.`news` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` text NOT NULL,
  `author` text NOT NULL,
  `content` longtext NOT NULL,
  `date` datetime NOT NULL,
  `url` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `database`.`npcs`;
CREATE TABLE  `database`.`npcs` (
  `npcid` int(10) unsigned NOT NULL,
  `link` varchar(45) NOT NULL,
  `hideName` int(10) unsigned NOT NULL,
  `dcLeft` int(10) unsigned NOT NULL,
  `dcTop` int(10) unsigned NOT NULL,
  `dcRight` int(10) unsigned NOT NULL,
  `dcBottom` int(10) unsigned NOT NULL,
  `trunkPut` int(10) unsigned NOT NULL,
  `talkMouseOnly` int(10) unsigned NOT NULL,
  `Ffloat` int(10) unsigned NOT NULL,
  `speed` int(10) unsigned NOT NULL,
  `dcBattom` int(10) unsigned NOT NULL,
  `0` longtext NOT NULL,
  `name` varchar(45) NOT NULL,
  `n0` longtext NOT NULL,
  `n1` longtext NOT NULL,
  `n2` longtext NOT NULL,
  `d0` longtext NOT NULL,
  `d1` longtext NOT NULL,
  `func` longtext NOT NULL,
  `s0` longtext NOT NULL,
  `s1` longtext NOT NULL,
  `s3` longtext NOT NULL,
  `s4` longtext NOT NULL,
  `f0` longtext NOT NULL,
  `h0` longtext NOT NULL,
  `h1` longtext NOT NULL,
  `h2` longtext NOT NULL,
  `a0` longtext NOT NULL,
  `i0` longtext NOT NULL,
  `l0` longtext NOT NULL,
  `q0` longtext NOT NULL,
  `b0` longtext NOT NULL,
  `c0` longtext NOT NULL,
  `f1` longtext NOT NULL,
  `f2` longtext NOT NULL,
  `w0` longtext NOT NULL,
  `w1` longtext NOT NULL,
  `w2` longtext NOT NULL,
  `n3` longtext NOT NULL,
  `l1` longtext NOT NULL,
  `c1` longtext NOT NULL,
  `e0` longtext NOT NULL,
  `m0` longtext NOT NULL,
  `t0` longtext NOT NULL,
  `a1` longtext NOT NULL,
  `g0` longtext NOT NULL,
  `g1` longtext NOT NULL,
  `f3` longtext NOT NULL,
  `m1` longtext NOT NULL,
  `t1` longtext NOT NULL,
  `wedding0` longtext NOT NULL,
  `wedding1` longtext NOT NULL,
  `wedding2` longtext NOT NULL,
  `wedding3` longtext NOT NULL,
  `wedding4` longtext NOT NULL,
  `rpsGame` int(10) unsigned NOT NULL,
  `parcel` int(10) unsigned NOT NULL,
  `storebank` int(10) unsigned NOT NULL,
  `trunkGet` int(10) unsigned NOT NULL,
  `guildRank` int(10) unsigned NOT NULL,
  `cash` int(10) unsigned NOT NULL,
  `dcmark` int(10) unsigned NOT NULL,
  `quest` varchar(45) NOT NULL,
  `MapleTV` int(10) unsigned NOT NULL,
  `MapleTVmsgY` int(10) unsigned NOT NULL,
  `MapleTVadX` int(10) unsigned NOT NULL,
  `MapleTVadY` int(10) unsigned NOT NULL,
  `noNpcShop` int(10) unsigned NOT NULL,
  `imitate` int(10) unsigned NOT NULL,
  `url` longtext NOT NULL,
  PRIMARY KEY (`npcid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `database`.`skills`;
CREATE TABLE  `database`.`skills` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `skillid` int(10) NOT NULL,
  `name` text NOT NULL,
  `bookName` text NOT NULL,
  `Rdesc` longtext NOT NULL,
  `h1` text NOT NULL,
  `h2` text NOT NULL,
  `h3` text NOT NULL,
  `h4` text NOT NULL,
  `h5` text NOT NULL,
  `h6` text NOT NULL,
  `h7` text NOT NULL,
  `h8` text NOT NULL,
  `h9` text NOT NULL,
  `h10` text NOT NULL,
  `h11` text NOT NULL,
  `h12` text NOT NULL,
  `h13` text NOT NULL,
  `h14` text NOT NULL,
  `h15` text NOT NULL,
  `h16` text NOT NULL,
  `h17` text NOT NULL,
  `h18` text NOT NULL,
  `h19` text NOT NULL,
  `h20` text NOT NULL,
  `h21` text NOT NULL,
  `h22` text NOT NULL,
  `h23` text NOT NULL,
  `h24` text NOT NULL,
  `h25` text NOT NULL,
  `h26` text NOT NULL,
  `h27` text NOT NULL,
  `h28` text NOT NULL,
  `h29` text NOT NULL,
  `h30` text NOT NULL,
  `icon` longtext NOT NULL,
  `masterLv` int(10) unsigned NOT NULL,
  `parent` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `database`.`worldmap`;
CREATE TABLE  `database`.`worldmap` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `worldmap` varchar(45) NOT NULL,
  `parentMap` varchar(45) NOT NULL,
  `BaseImg` longtext NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `database`.`worldmap_maplink`;
CREATE TABLE  `database`.`worldmap_maplink` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `worldmap` varchar(45) NOT NULL,
  `linkImg` longtext NOT NULL,
  `linkMap` varchar(45) NOT NULL,
  `tooltip` varchar(45) NOT NULL,
  `originX` int(10) NOT NULL,
  `originY` int(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `database`.`worldmap_maplist`;
CREATE TABLE  `database`.`worldmap_maplist` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `worldmap` varchar(45) NOT NULL,
  `mapNo` int(10) unsigned NOT NULL,
  `spotX` int(11) NOT NULL,
  `spotY` int(11) NOT NULL,
  `type` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `database`.`wz_questactdata`;
CREATE TABLE  `database`.`wz_questactdata` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `questid` int(11) NOT NULL DEFAULT '0',
  `name` varchar(127) NOT NULL DEFAULT '',
  `type` tinyint(1) NOT NULL DEFAULT '0',
  `intStore` int(11) NOT NULL DEFAULT '0',
  `applicableJobs` varchar(1024) NOT NULL DEFAULT '',
  `uniqueid` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `quests_ibfk_2` (`questid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `database`.`wz_questactitemdata`;
CREATE TABLE  `database`.`wz_questactitemdata` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemid` int(11) NOT NULL DEFAULT '0',
  `count` smallint(5) NOT NULL DEFAULT '0',
  `period` int(11) NOT NULL DEFAULT '0',
  `gender` tinyint(1) NOT NULL DEFAULT '2',
  `job` int(11) NOT NULL DEFAULT '-1',
  `jobEx` int(11) NOT NULL DEFAULT '-1',
  `prop` int(11) NOT NULL DEFAULT '-1',
  `uniqueid` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `database`.`wz_questactquestdata`;
CREATE TABLE  `database`.`wz_questactquestdata` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `quest` int(11) NOT NULL DEFAULT '0',
  `state` tinyint(1) NOT NULL DEFAULT '2',
  `uniqueid` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `database`.`wz_questactskilldata`;
CREATE TABLE  `database`.`wz_questactskilldata` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `skillid` int(11) NOT NULL DEFAULT '0',
  `skillLevel` int(11) NOT NULL DEFAULT '-1',
  `masterLevel` int(11) NOT NULL DEFAULT '-1',
  `uniqueid` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `database`.`wz_questdata`;
CREATE TABLE  `database`.`wz_questdata` (
  `questid` int(11) NOT NULL,
  `name` varchar(1024) NOT NULL DEFAULT '',
  `autoStart` tinyint(1) NOT NULL DEFAULT '0',
  `autoPreComplete` tinyint(1) NOT NULL DEFAULT '0',
  `viewMedalItem` int(11) NOT NULL DEFAULT '0',
  `selectedSkillID` int(11) NOT NULL DEFAULT '0',
  `blocked` tinyint(1) NOT NULL DEFAULT '0',
  `autoAccept` tinyint(1) NOT NULL DEFAULT '0',
  `autoComplete` tinyint(1) NOT NULL DEFAULT '0',
  `url` longtext NOT NULL,
  PRIMARY KEY (`questid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `database`.`wz_questreqdata`;
CREATE TABLE  `database`.`wz_questreqdata` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `questid` int(11) NOT NULL DEFAULT '0',
  `name` varchar(127) NOT NULL DEFAULT '',
  `type` tinyint(1) NOT NULL DEFAULT '0',
  `stringStore` varchar(1024) NOT NULL DEFAULT '',
  `intStoresFirst` varchar(1024) NOT NULL DEFAULT '',
  `intStoresSecond` varchar(1024) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `quests_ibfk_1` (`questid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;